const DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED";
const SEARCHED_TODOS = "SEARCHED_TODOS";
const TODO_ADDED = "TODO_ADDED";

const TODO_REMOVED = "TODO_REMOVED";
const TODO_MARKED_AS_DONE = "TODO_MARKED_AS_DONE";
const TODO_MARKED_AS_PENDING = "TODO_MARKED_AS_PENDING";

export {
  DESCRIPTION_CHANGED,
  SEARCHED_TODOS,
  TODO_ADDED,
  TODO_REMOVED,
  TODO_MARKED_AS_DONE,
  TODO_MARKED_AS_PENDING,
};
